name: Deploy to VPS and run dev 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # install node.js
      - name: Install node.js
        uses: actions/setup-node@main
        with:
          node-version: lts/*
          
      # install dependencies
      - name: Install dependencies
        run: npm i
      
      # Deploy to server
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          # private key
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # SCP
          ARGS: '-avzr'
          # server ip
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # user
          REMOTE_USER: 'root'
          # target
          TARGET: "/root/openai/gpt-backend"

      # will take care test and run later
      - name: Executing remote ssh commands to start the project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            whoami
            ls -la
            cd openai/gpt-backend/
            npm run start 
            nohup npm run start > output.log 2>&1 &